### ISSUE TITLE
兄弟，你这个括号

### ISSUE THREAD

**Issue by chym123** [skillnull/Get-Device-Info#1]
https://github.com/skillnull/GetDeviceInfo/blob/91809600013e69c744a0ab334e94365c3d0b6e15/getDeviceInfo.js#L43

加括号会搞两个匹配啊，一个是匹配组一个是全匹配。

**Comment by skillnull** [comment]
> https://github.com/skillnull/GetDeviceInfo/blob/91809600013e69c744a0ab334e94365c3d0b6e15/getDeviceInfo.js#L43
> 
> 加括号会搞两个匹配啊，一个是匹配组一个是全匹配。

多谢指出，已修复
