### ISSUE TITLE
大神你好

### ISSUE THREAD

**Issue by kingking888** [skillnull/Get-Device-Info#3]
小白提问：
useragent是已经添加进生成指纹对象了吗？useragent很容易伪造。

1.是否可以添加定位？
2.是否可以添加时间？
3.是否可以添加uuid？

**Comment by skillnull** [comment]
> 小白提问：
> useragent是已经添加进生成指纹对象了吗？useragent很容易伪造。
> 
> 1.是否可以添加定位？
> 2.是否可以添加时间？
> 3.是否可以添加uuid？

1.浏览器指纹是根据domain利用canvas生成
2.时间、定位、uuid后续会陆续添加
