### ISSUE TITLE
360浏览器识别不出来移动端和PC端

### ISSUE THREAD

**Issue by Mrwangfan** [skillnull/Get-Device-Info#4]
// 判段360浏览器
            mime(option, value) {
                var mimeTypes = navigator.mimeTypes;
                for (var mt in mimeTypes) {
                    if (mimeTypes[mt][option] == value) {
                        return true;
                    }
                }
                return false;
            } 
PC用这个解决了 但是移动端用这个不行

**Comment by skillnull** [comment]
> // 判段360浏览器
> mime(option, value) {
> var mimeTypes = navigator.mimeTypes;
> for (var mt in mimeTypes) {
> if (mimeTypes[mt][option] == value) {
> return true;
> }
> }
> return false;
> }
> PC用这个解决了 但是移动端用这个不行

你好，你可以查看一下移动端的浏览器内核，以及userAgent然后添加到具体的方法内即可，目前只做了部分浏览器的适配
